name: Generate Snake

on:
  schedule: # Ejecutar automáticamente cada día a las 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Permitir ejecución manual

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk/svg-only@v3
        id: snake-gif
        with:
          github_user_name: LChumi
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - run: git status

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist